[package]
name = "freedesktop-desktop-entry"
version = "0.4.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"
homepage = "https://github.com/pop-os/freedesktop-desktop-entry"
description = "Freedesktop Desktop Entry Specification"
license = "MPL-2.0"
readme = "README.md"
categories = [ "os::unix-apis" ]
keywords = [ "freedesktop", "desktop", "entry" ]
maintenance = { status = "passively-maintained" }

[dependencies]
dirs = "3"
gettext-rs = { version = "0.7", features = ["gettext-system"]}
memchr = "2"
thiserror = "1"
