[package]
name = "freedesktop-desktop-entry"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"
homepage = "https://github.com/pop-os/freedesktop-desktop-entry"
repository = "https://github.com/pop-os/freedesktop-desktop-entry"
description = "Freedesktop Desktop Entry Specification"
license = "MIT/Apache-2.0"
readme = "README.md"
categories = [ "os::unix-apis" ]
keywords = [ "freedesktop", "desktop", "entry" ]

[dependencies]
markup = "0.3.1"
